'''
Data can be posted to url and it will be displayed
The URL is public facing URL generated by ngork

'''
from flask import Flask, request
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)

@app.route('/', methods=["POST"])
def index():
    if request.data:
        print(request.data)
        return request.data


if __name__ == '__main__':
    app.run()
